language: python
python: 
	- 3.5
    - pypy
sudo: false
env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=py35
- TOXENV=pypy
install:
- pip install tox
- pip install -U cython
script:
- ./update_cpp.sh
- tox
